### PR TITLE
Minor Changes to FV and Formatting

### PR DESCRIPTION
**Pull request by remedcu**
This PR updates a few things for #47 

- Formatting `README` and adding details to run FV.
- Ordering `GuardianStorage.spec` contents.
- Updating the `conf` file of FV.
- Upgrading certora version to 7.6.3

No new FV rule/invariant is introduced.

### CODE REVIEW

**Comment by akshay-ap** [comment]
Unrelated to the issue the PR is addressing but, I have some suggestions for README.md as I can't suggest at unchanged lines. These may be covered in another PR but, I am writing here.

- [ ] Typo:
       An interface without a backend service can simply let each guardian submit their signatures separately. Once the threshold is ~~meant~~ met, anyone can call execute recovery to start the recovery period.
- [ ] Contradictory statements
      A typical single-owner account can have 3 guardians with a threshold of 2. This increases the likelihood that a single guardian can overtake the account.
- [ ] Nit
     The Account Recovery module is designed to work for both a single-owner account and an ~~n-m~~ n/m multi-sig account
- [ ] I think `addresses` is the correct term instead of `methods`
    More specifically, owners can add recovery ~~methods~~ addresses (also known as Guardians) to change the ownership of the account, in case their signer key is lost or compromised.
- [ ] Would be nice to have a sequence diagram to show the complete flow like we have for passkey and 4337 modules
- [ ] I don't understand how possibility of malicious guardian co-operating with owner is eliminated with fresh address?
       
```
       Owners are encouraged to ask their guardians to provide fresh addresses. This makes them private and eliminates the possibility of malicious guardians cooperating against an owner.
```
- [ ] README does not mention anything about delay period and that user has the power to cancel any recovery if they wish to.

**Review by nlordell — APPROVED** [review]

**Review by mmv08 — APPROVED** [review]

**Comment by remedcu** [comment]
> * [ ]  Typo:
>   An interface without a backend service can simply let each guardian submit their signatures separately. Once the threshold is ~meant~ met, anyone can call execute recovery to start the recovery period.

Nice catch!

> * [ ]  Contradictory statements
>   A typical single-owner account can have 3 guardians with a threshold of 2. This increases the likelihood that a single guardian can overtake the account.

Agreed.
Recommended change:
```
This decreases the likelihood that a single guardian can overtake the account.
```

> * [ ]  Nit
>   The Account Recovery module is designed to work for both a single-owner account and an ~n-m~ n/m multi-sig account

Don't have a strong opinion on this one.

> * [ ]  I think `addresses` is the correct term instead of `methods`
>   More specifically, owners can add recovery ~methods~ addresses (also known as Guardians) to change the ownership of the account, in case their signer key is lost or compromised.

Agreed.

> * [ ]  Would be nice to have a sequence diagram to show the complete flow like we have for passkey and 4337 modules

@nlordell should we add this for the upstream?

> * [ ]  I don't understand how possibility of malicious guardian co-operating with owner is eliminated with fresh address?
> 
> ```
>        Owners are encouraged to ask their guardians to provide fresh addresses. This makes them private and eliminates the possibility of malicious guardians cooperating against an owner.
> ```

I think he meant not using accounts that can be linked back to the guardian (Ex: ENS names which are popular enough to find who that address might be related to).

> * [ ]  README does not mention anything about delay period and that user has the power to cancel any recovery if they wish to.

Nice catch, can be added.

**Comment by nlordell** [comment]
> I think he meant not using accounts that can be linked back to the guardian (Ex: ENS names which are popular enough to find who that address might be related to).

Correct, it makes it harder for guardians to collude (they don't know which other guardians to ask, and asking around could raise suspicion of the owner). I think the sentence is fine as-is.

**Comment by nlordell** [comment]
> Recommended change:

:+1: 

> Don't have a strong opinion on this one.

I would leave it as is - I think this is up to style and the Candide team chose to express it this way.

>  Would be nice to have a sequence diagram to show the complete flow like we have for passkey and 4337 modules

We can ask the Candide team to do this IMO.

**Pull request merged**
