### PR TITLE
Update the Certora CI to run only when Key is available

### PR DESCRIPTION
**Pull request by remedcu**
This PR updates the Certora CI workflow to only run when there is a valid key available, else will skip the CI Check.

### CODE REVIEW

**Comment by mmv08** [comment]
why is this needed?

**Comment by remedcu** [comment]
> why is this needed?

https://github.com/candidelabs/candide-contracts/pull/23#issuecomment-2194416998

**Comment by nlordell** [comment]
To facilitate upstreaming to the Candide repo (so the CI doesn't always fail). I think this should be included in the PR description (in general, I think PR descriptions shouldn't just include "what?" which is - hopefully - clear from the change set itself, but the context and rationale of the change).

**Comment by mmv08** [comment]
Is there a way to solve this differently? I imagine the action passing without the key is good for the Candide repo, but if we forget to configure the key, it should fail in our repo.

**Comment by remedcu** [comment]
> Is there a way to solve this differently? I imagine the action passing without the key is good for the Candide repo, but if we forget to configure the key, it should fail in our repo.

I agree, working on a better elegant solution: https://github.com/remedcu/CandideWalletContracts/pull/1

This PR will be closed now.

**Comment by akshay-ap** [comment]
> Is there a way to solve this differently? I imagine the action passing without the key is good for the Candide repo, but if we forget to configure the key, it should fail in our repo.

I think adding an additional secret e.g `SAFE_GLOBAL_REPO=true` that indicates the repository is maintained by Safe team and checking this flag should accomplish this. So, if `SAFE_GLOBAL_REPO=true` and `CERTORAKEY=null` CI should fail

EDIT: My comment came in late. https://github.com/remedcu/CandideWalletContracts/pull/1/files is better

**Comment by mmv08** [comment]
> > Is there a way to solve this differently? I imagine the action passing without the key is good for the Candide repo, but if we forget to configure the key, it should fail in our repo.
> 
> I think adding an additional secret e.g `SAFE_GLOBAL_REPO=true` that indicates the repository is maintained by Safe team and checking this flag should accomplish this. So, if `SAFE_GLOBAL_REPO=true` and `CERTORAKEY=null` CI should fail

I think you can also get the repository owner from the context: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

And add an additional check for the repo owner or name

**Pull request closed without merging**
